remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Andrew Butler
logo: /assets/img/logo.png
description: Forecasts for the MSE gradient boosting and dboost prediction models.
show_downloads: false
